<?php

namespace App\Models;

use App\CentralLogics\Helpers;
use App\Models\GeneralSetting;
use App\Models\Rating;
use Auth;
use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Cashier\Billable;
use Laravel\Sanctum\HasApiTokens;
use App\Models\Transaction;

use App\Models\Order;
use App\Models\UserActivity;
use App\Models\SubPlan;
use App\Models\UserSubscription;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, Billable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'google_id',
        'name',
        'email',
        'password',
        'affiliate_code',
        'code',
        'phone',
        'role_id',
        'referred_by',
        'discount',
        'oauth_uid',
        'oauth_provider',
        'stripe_customer_id',
        'has_paid_resume_builder',
        'promotional_emails',
        'created_at',
        'updated_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function country()
    {
          return $this->belongsTo(Country::class, 'country_id');
    }
    
    // Relationship to Referral
    public function referrals()
    {
        // Assuming 'referral_id' is the field in the users table that stores the ID of the user who referred them
        return $this->hasMany(User::class, 'referred_by', 'affiliate_code');
    }

    // Relationship to Orders
    public function orders()
    {
        // Assuming each order stores a 'user_id' to link to the user
        return $this->hasMany(Order::class, 'user_id', 'id');
    }

    // Relationship to UserSubscriptions
    public function subscriptions()
    {
        return $this->hasMany(UserSubscription::class, 'user_id', 'id');
    }

    // Relationship to Orders
    public function transactions()
    {
        // Assuming each order stores a 'user_id' to link to the user
        return $this->hasMany(Transaction::class, 'user_id', 'id');
    }

    // Get the count of unique users referred by this user
    public function getUniqueUserCount()
    {
        return $this->referrals()->count();
    }

    // Get the total sales generated by referrals
    public function getTotalSalesFromReferrals()
    {
        $sales=Transaction::where('referrer_link', $this->affiliate_code)->sum('amount');
        return $sales;
    }


    public function activePlan()
    {
        return $this->hasOne(UserSubscription::class)
            ->where('status', 'active')
            ->where(function ($query) {
                $query->whereNull('expires_at')
                      ->orWhere('expires_at', '>', now());
            })
            ->orderBy('id', 'desc');
    }

    public function subscriptionsActive()
    {
        return $this->hasOne(UserSubscription::class)
            ->where('status', 'active')
            ->where(function ($query) {
                $query->whereNull('expires_at')
                      ->orWhere('expires_at', '>', now());
            })
            ->orderBy('id', 'desc')
            ->first();
    }

    public function activateFreePlan()
    {
        $plan = SubPlan::where('slug', 'free-plan')->firstOrFail();
        
        $token = substr(str_shuffle(str_repeat("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ", 5)), 0, 5) . '-' . time();
        
        // Handle access_section - it might be already an array due to Eloquent casting
        if (is_array($plan->access_section)) {
            $access_section = $plan->access_section;
            $access_section_json = $plan->access_section; // Already an array, will be json_encode'd in create
        } else {
            $access_section = json_decode($plan->access_section, true);
            $access_section_json = $plan->access_section;
        }
        
        // Since this is a free plan, we can set the expiry date to null or a specific time if required
        $expiryDate = null; // or now()->addMonth() if you want to give it a time frame

        $order = Order::create([
            'user_id' => $this->id,
            'plan_id' => $plan->id,
            'amount' => $plan->price,
            'payment_id' => "free-plan", // No payment for the free plan
            'token' => $token,
            'expires_at' => $expiryDate,
            'access_section' => $access_section_json,
        ]);

        // Create user subscription record for free plan
        UserSubscription::create([
            'user_id'        => $this->id,
            'plan_id'        => $plan->id,
            'plan_slug'      => $plan->slug,
            'amount'         => $plan->price,
            'payment_id'     => 'free-plan',
            'token'          => $token,
            'starts_at'      => now(),
            'expires_at'     => $expiryDate,
            'access_section' => json_encode($access_section),
            'features_used'  => [],
            'status'         => 'active',
        ]);

        // Initialize user activity tracking
        UserActivity::create([
            'user_id' => $this->id,
            'order_id' => $order->id,
        ]);
    }

    //****************User Transaction & Balance Modules****************//
    protected  function activeTransaction() {
        $gs=GeneralSetting::find(1);
        $user=Auth::user();
        $datenow=Carbon::now()->subDays($gs->withdrawl_after_days);

        return $earning_net_user=Transaction::where('referrer_link',$user->affiliate_code)
               ->where('status','active')
               ->where('created_at','<=',$datenow)
               ->where('is_cleared',0); //2<=-25
               // ->where('is_cleared',0)
               // ->sum('earning_net_user');
    }
    public  function userbalance($withCurrency='') {

        $activeTransaction=$this->activeTransaction();
        $earning_net_user=0;
        if($activeTransaction){
            $earning_net_user=$activeTransaction->sum('earning_net_user');
        }

        if($withCurrency && $withCurrency==1){
          return Helpers::setCurrency($earning_net_user);
        }else{
            return $earning_net_user;
        }                      
    }
    public function userbalancedecrement($value='')
    {  
        $activeTransaction=$this->activeTransaction();
      
        if($activeTransaction){
            $activeTransaction->update(['is_cleared'=>1]);
        }
    }
    //****************User Transaction & Balance Modules****************//

    public function placementProfile()
    {
        return $this->hasOne(PlacementProfile::class);
    }

    public function coverLetters()
    {
        return $this->hasMany(CoverLetter::class);
    }

    public function resumeSubscriptions()
    {
        return $this->hasMany(ResumeSubscription::class);
    }

    /**
     * Get active subscription from UserSubscription table
     */
    public function getActiveSubscription()
    {
        return $this->subscriptions()
                    ->where('status', 'active')
                    ->where(function ($query) {
                        $query->whereNull('expires_at')
                              ->orWhere('expires_at', '>', now());
                    })
                    ->orderBy('id', 'desc')
                    ->first();
    }

    /**
     * Check if user has active subscription
     */
    public function hasActiveSubscription()
    {
        return $this->getActiveSubscription() !== null;
    }

    /**
     * Get promo codes assigned to this user
     */
    public function promoCodes()
    {
        return $this->belongsToMany(PromoCode::class, 'promo_code_user')
                    ->withPivot('used', 'used_at')
                    ->withTimestamps();
    }

    /**
     * Get active (unused) promo codes for this user
     */
    public function getActivePromoCodes()
    {
        return $this->promoCodes()
                    ->where('active', true)
                    ->where(function ($query) {
                        $query->whereNull('expires_at')
                              ->orWhere('expires_at', '>', now());
                    })
                    ->wherePivot('used', false)
                    ->get();
    }

    /**
     * Get a specific promo code validity for this user
     */
    public function canUsePromoCode($code): bool
    {
        $promoCode = PromoCode::where('code', strtoupper($code))->first();

        if (!$promoCode) {
            return false;
        }

        return $promoCode->canUserUse($this);
    }
}
